DEFAULT_REGION = 'eu-west-1'
DEFAULT_AVAILABILITY_ZONE = 'eu-west-1a'

EC2_KEY_PAIR_NAME = 'Cloud Automation and Orchestration'

WINDOWS_AMI_ID = 'ami-0c0dd5ec2d91c4221'
UBUNTU_AMI_ID = 'ami-049442a6cf8319180'
DEFAULT_EC2_INSTANCE_TYPE = 't3.micro'

DEFAULT_VOLUME_TYPE = 'gp2'
DEFAULT_VOLUME_SIZE_GIB = 8

DEFAULT_DEVICE_NAME = '/dev/sdf'

DEFAULT_SNAPSHOT_NAME = 'Created from EBSController'

DEFAULT_NAMESPACE = 'AWS/EC2'

DEFAULT_RDS_DB_INSTANCE_CLASS = 'db.t4g.micro'
DEFAULT_DB_STORAGE_GIB = 20

DATETIME_FORMAT = '%Y-%m-%d %H:%M:%S'
DATETIME_COMPACT_FORMAT = '%Y%m%d%H%M%S'
